Gui:
  custom-item: false
  enabled: true # Set false to enable baltop in chat
  title: "&5Top 10"
  size: 27
  items:
    player-item:
      name: "&a{name} &d#{order}"
      lore:
        - "&8Item"
        - ""
        - "&7Balance: &e{balance}"
    close-menu:
      slot: 8
      material: "STONE_BUTTON"
      name: "&cClose the menu!"
      lore:
        - "&8Item"
        - ""
        - "&7&oClick to close menu."
    player-not-found:
      material: "BARRIER"
      name: "&cPlayer not found!"
      lore:
        - "&8Item"
        - ""
        - "&7&oPlayer not found."
    self-item:
      slot: 0
      material: "GHAST_TEAR" # Only works when custom-item enabled!! (same with Tops.#.material)
      name: "&e&lYou"
      lore:
        - "&8Item"
        - ""
        - "&7Balance: &e{balance}"
        - "&7Order: &e{order}"
    fill:
      enabled: true
      material: "GRAY_STAINED_GLASS_PANE"

Messages:
  gui-opened:
    status: true
    message: "&aGui opened"
  reloaded: "&aConfig reloaded!"
  no-perm: "&cYou do not have enough permission for that!"

  chat-baltop-header: "&8&m-----------------[&r &6&lBALTOP &8&m]-----------------"
  chat-baltop-format: "&7#{order}&8, &b{name} &7- &b{balance}"
  chat-baltop-footer: "&8&m--------------------------------------------"

Tops:
  '1':
    material: "EMERALD_BLOCK" # Only works when custom-item enabled
    slot: 4
    order: 1
  '2':
    material: "DIAMOND_BLOCK"
    slot: 12
    order: 2
  '3':
    material: "GOLD_BLOCK"
    slot: 14
    order: 3
  '4':
    material: "IRON_BLOCK"
    slot: 19
    order: 4
  '5':
    material: "COAL_BLOCK"
    slot: 20
    order: 5
  '6':
    material: "EMERALD_INGOT"
    slot: 21
    order: 6
  '7':
    material: "DIAMOND"
    slot: 22
    order: 7
  '8':
    material: "GOLD_INGOT"
    slot: 23
    order: 8
  '9':
    material: "IRON_INGOT"
    slot: 24
    order: 9
  '10':
    material: "COAL"
    slot: 25
    order: 10